name: kertaskerja
services:
    kertaskerja:
        build: .
        image: kertaskerja
        container_name: kertaskerja
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
volumes:
    caddy_data:
    caddy_config:
