services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: atp
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
